[build]
  command = """
  npm cache clean --force &&
  npm install --prefix optometrists-companion-web-homepage &&
  npm install --prefix The-Optometrists-Companion &&
  cd optometrists-companion-web-homepage &&
  npx gatsby build &&
  cd ../The-Optometrists-Companion &&
  npm install &&
  expo export &&
  cd .. &&
  mkdir -p combined-build &&
  cp -R optometrists-companion-web-homepage/public/* combined-build/ &&
  cp -R The-Optometrists-Companion/web-build/* combined-build/
  """
  publish = "combined-build"

  # Specify Node.js version
[context.production.environment]
  NODE_VERSION = "20.10.0" # Replace with your required Node.js version