[build]
  command = "node build.js"
  publish = "web-build/gatsby"

[[redirects]]
  from = "/gatsby/*"
  to = "/gatsby/:splat"
  status = 200
  force = false

[[redirects]]
  from = "/expo-app/*"
  to = "/expo-app/:splat"
  status = 200
  force = false
