[build]
  command = "node build.js"
  publish = "web-build"

[[redirects]]
  from = "/expo-app/*"
  to = "/expo-app/:splat"
  status = 200
  force = false

[[redirects]]
  from = "/gatsby/*"
  to = "/gatsby/:splat"
  status = 200
  force = false

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true  # Ensure that the root redirects do not interfere with specific app paths