[build]
  command = "npm install --prefix optometrists-companion-web-homepage && npm install --prefix The-Optometrists-Companion && cd optometrists-companion-web-homepage && npx gatsby build && cd ../The-Optometrists-Companion && expo export"
  publish = "path-to-publish-directory"
