[build]
  command = "node build.js"
  publish = "web-build"

[[redirects]]
  from = "/*"
  to = "/:splat"
  status = 200
  force = false

[[redirects]]
  from = "/expo-app/*"
  to = "/expo-app/:splat"
  status = 200
  force = false